dovecot_config_version = 2.4.2
dovecot_storage_version = 2.4.0
ssl = required
ssl_server_cert_file = /mail/fullchain.pem
ssl_server_key_file = /mail/privkey.pem
ssl_cipher_list = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-ARIA256-GCM-SHA384:ECDHE-ARIA256-GCM-SHA384:DHE-RSA-ARIA256-GCM-SHA384
auth_mechanisms = plain login
auth_username_format = %{user | username | lower}
recipient_delimiter = +-.

mail_driver = maildir
mail_path = /mail/%{user | username | lower}
mail_inbox_path = Inbox
mailbox_list_layout = fs
protocols = imap lmtp

userdb passwd-file {
    passwd_file_path = /mail/users.passwd
    auth_username_format = %{user | username | lower}
}
passdb passwd-file {
    passwd_file_path = /mail/users.passwd
    auth_username_format = %{user | username | lower}
}

namespace inbox {
    inbox = yes
    mailbox Drafts {
        special_use = \Drafts
        auto = subscribe
    }
    mailbox Sent {
        special_use = \Sent
        auto = subscribe
    }
    mailbox Trash {
        special_use = \Trash
    }
}

service auth {
    unix_listener /var/spool/postfix/private/auth {
        mode = 0660
        user = postfix
        group = postfix
    }
}

service lmtp {
    unix_listener /var/spool/postfix/private/dovecot-lmtp {
        mode = 0600
        user = postfix
        group = postfix
    }
}

log_path = /mail/dovecot.log
