FROM curlimages/curl:latest

ENV TOKEN=
ENV DOMAIN=rosenhof.chrissx.de
ENV ZONE=08bd4c50de27d76b981bfe6b8c911a97
ENV RECORD4=6016d3dd55f04e871a5ef61df41f52d0
ENV RECORD6=48947dfa2a193ad6082766334e0c982f

COPY dyndns /usr/local/bin/dyndns
CMD /usr/local/bin/dyndns
