#!/bin/sh
set -uxe

LAST4=
LAST6=

while true ; do
        IP4=`curl -4 http://sophia.chrissx.de:8080`
        IP6=`curl -6 http://sophia.chrissx.de:8080 | sed 's/\[//;s/\]//'`

        if [ "$LAST4" != "$IP4" ] ; then
                curl -L -H "Authorization: Bearer $TOKEN" \
                        -H "Content-Type: application/json" \
                        --data '{"type":"A","name":"'"$DOMAIN"'","content":"'"$IP4"'","ttl":120,"proxied":false}' \
                        -X PUT \
                        "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records/$RECORD4"
                LAST4="$IP4"
        fi

        if [ "$LAST6" != "$IP6" ] ; then
                curl -L -H "Authorization: Bearer $TOKEN" \
                        -H "Content-Type: application/json" \
                        --data '{"type":"AAAA","name":"'"$DOMAIN"'","content":"'"$IP6"'","ttl":120,"proxied":false}' \
                        -X PUT \
                        "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records/$RECORD6"
                LAST6="$IP6"
        fi

        sleep 60
done
