server {
	include conf.d/server;
	server_name status-ruby.chrissx.de status.chrissx.de;
	ssl_certificate /etc/letsencrypt/live/chrissx.de/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/chrissx.de/privkey.pem;

	location / {
		proxy_pass http://kuma:3001;
		include conf.d/proxy_params;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
