type = "notification"
name = "Email"
active = true
is_default = false

[config]
type = "smtp"
smtpHost = '''"{{ get_env(name='AUTOKUMA__ENV__SMTP_HOST') | json_encode | split(pat='') | slice(start=2, end=-2) | join(sep='') }}"'''
smtpPort = 465
smtpSecure = true
smtpIgnoreTLSError = false
smtpUsername = '''"{{ get_env(name='AUTOKUMA__ENV__SMTP_USERNAME') | json_encode | split(pat='') | slice(start=2, end=-2) | join(sep='') }}"'''
smtpPassword = '''"{{ get_env(name='AUTOKUMA__ENV__SMTP_PASSWORD') | json_encode | split(pat='') | slice(start=2, end=-2) | join(sep='') }}"'''
smtpFrom = '''"{{ get_env(name='AUTOKUMA__ENV__SMTP_USERNAME') | json_encode | split(pat='') | slice(start=2, end=-2) | join(sep='') }}"'''
smtpTo = '''"{{ get_env(name='AUTOKUMA__ENV__SMTP_TO') | json_encode | split(pat='') | slice(start=2, end=-2) | join(sep='') }}"'''
customSubject = '''[{{ get_env(name='AUTOKUMA__ENV__SITE') }}] {% raw %}{{ status }} {{ name }}{% endraw %}'''
applyExisting = false
