#!/bin/sh
curl -L https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/install_sources.sh | sh
sudo apt install -y apache2 pygopherd certbot
sudo service pygopherd stop
sudo rm -rf /var/gopher
sudo git clone https://github.com/chrissxYT/chrissx.de-70.git /var/gopher
sudo service pygopherd start
sudo service pygopherd enable
sudo service apache2 stop
sudo rm -rf /var/www/html
sudo git clone https://github.com/chrissxYT/chrissx.de.git /var/www/html &
sudo git clone https://github.com/Ampless/ampless.chrissx.de.git /var/www/ampless &
sudo git clone https://github.com/chrissxYT/apt.chrissx.de.git /var/www/apt &
sudo git clone https://github.com/chrissxYT/zerm.eu.git /var/www/zerm &
sudo curl -Lo /etc/apache2/sites-enabled/default-ssl.conf https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/apache2/default-ssl.conf &
sudo curl -Lo /etc/apache2/apache2.conf https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/apache2/apache2.conf &
sudo a2enmod ssl http2 headers proxy proxy_http proxy_http2 &
curl -L https://github.com/chrissxYT/chrissx.de-80/raw/master/install.sh | sudo sh &
curl -L https://github.com/chrissxYT/zerm.link/raw/master/install.sh | sudo sh &
sudo openssl dhparam -out /etc/ssl/private/dhparams.pem 4096 &
echo "schedule downtime, change router settings and press enter"
read _quatschistan
wait
sudo certbot certonly --standalone -d 'chrissx.de www.chrissx.de chrissx.eu www.chrissx.eu ampless.chrissx.de amplus.chrissx.de apt.chrissx.de i3b.chrissx.de git.chrissx.de meme.chrissx.de penis.chrissx.de www.zerm.eu zerm.eu zerm.link'
sudo service apache2 start
sudo service apache2 enable
echo "enter cloudflare api key"
read api_key
curl -L https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/home/dyndns.sh | sed "s/WHATEVER/$api_key/" > dyndns.sh
chmod +x dyndns.sh
curl -LO https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/home/gitpull.sh
chmod +x gitpull.sh
echo "tmux
./dyndns.sh
<C-B>csudo ./gitpull.sh
<C-B>d<C-D>"
