#!/bin/sh
newservice() {
    echo "[Unit]
Description=$2

[Service]
Type=simple
Restart=always
ExecStart=/usr/local/bin/$1

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/system/$1.service >/dev/null

    sudo systemctl enable --now $1.service
}

sudo apt update
sudo apt upgrade -y
sudo apt install -y git apache2 pygopherd certbot
sudo openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
sudo systemctl stop pygopherd.service
sudo rm -rf /var/gopher
sudo git clone https://github.com/chrissxYT/chrissx.de-70.git /var/gopher
sudo systemctl enable --now pygopherd.service
sudo systemctl stop apache2.service
sudo rm -rf /var/www/*
sudo git clone https://github.com/chrissxYT/chrissx.de.git /var/www/html
sudo git clone https://github.com/chrissxYT/meme.chrissx.de.git /var/www/meme
sudo git clone https://github.com/Ampless/ampless.chrissx.de.git /var/www/ampless
sudo git clone https://github.com/Amplus2/amplus.chrissx.de.git /var/www/amplus
sudo git clone https://github.com/ZERMZeitung/zerm.eu.git /var/www/zerm.eu
sudo rm -f /etc/apache2/sites-enabled/*
sudo curl -Lo /etc/apache2/sites-enabled/default-ssl.conf https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/apache2/default-ssl.conf
sudo curl -Lo /etc/apache2/apache2.conf https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/apache2/apache2.conf
sudo curl -Lo /etc/apache2/ports.conf https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/apache2/ports.conf
sudo a2enmod ssl http2 headers proxy proxy_http proxy_http2
curl -Lo red.deb https://github.com/chrissxYT/redirector/releases/download/3.3/redirector_3.3_linux_armv6.deb
sudo dpkg -i red.deb
newservice redirector "A simple HTTPS upgrador"
echo "schedule downtime, change router settings and press enter"
read _quatschistan
wait
sudo certbot certonly --standalone -d 'chrissx.de,www.chrissx.de,chrissx.eu,www.chrissx.eu,ampless.chrissx.de,amplus.chrissx.de,apt.chrissx.de,bucket.chrissx.de,i3b.chrissx.de,git.chrissx.de,meme.chrissx.de,penis.chrissx.de,www.zerm.eu,zerm.eu,zerm.link'
sudo systemctl enable --now apache2.service
echo "enter cloudflare api key"
read api_key
curl -L https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/home/dyndns.sh | sed "s/WHATEVER/$api_key/" > /usr/local/bin/dyndns
curl -Lo /usr/local/bin/gitpull https://github.com/chrissxYT/chrissx.de.conf.sh/raw/master/home/gitpull.sh
chmod +x /usr/local/bin/dyndns /usr/local/bin/gitpull
newservice dyndns dyndns
newservice gitpull gitpull
