name: Build and publish new containers

on:
  push:
    branches: [master]

jobs:
  ludwig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker/setup-qemu-action@v2.2.0
      - uses: docker/setup-buildx-action@v2.6.0
      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ludwig
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: chrissx/ludwig:latest
  simon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker/setup-qemu-action@v2.2.0
      - uses: docker/setup-buildx-action@v2.6.0
      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: simon
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: chrissx/simon:latest
  ali:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: docker/setup-qemu-action@v2.2.0
      - uses: docker/setup-buildx-action@v2.6.0
      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          context: ali
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: chrissx/ali:latest
